[package]
name = "support-kit"
version = "0.0.1"
edition = "2021"

[dependencies]
bon = { workspace = true }
clap = { workspace = true }
dirs = { workspace = true }
convert_case = { workspace = true }
figment = { workspace = true }
nutype = { workspace = true }
owo-colors = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-appender = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
figment = { workspace = true, features = ["test"] }
