[package]
name = "consumer"
version = "0.1.1"
publish = false
edition = "2021"

[dependencies]
support-kit = { workspace = true }
clap = { workspace = true }
owo-colors = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
