[package]
name = "logs"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
clap = { workspace = true }
support-kit = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
