name: Container
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: {{ '${{ github.actor }}' }}
          password: {{ '${{ secrets.' + token_name + ' }}' }}
      - run: {{ "rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}" }}
      - run: cargo xtask container build
      - run: cargo xtask container push
