name: Lint & Test
on:
  pull_request:
    branches:
      - main
env:
  RUSTFLAGS: "-Dwarnings"
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v4
      - run: {{ "rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}" }}
      - run: cargo check --all-targets --all-features
      - run: cargo test
      - run: cargo clippy --all-targets --all-features